"""
train.py
--------
Fine-tunes a DistilBERT model on repository summaries for technology
maturity classification (Track B).

Input : data/splits/train.csv, data/splits/val.csv
Output: models/trained_models/

The pipeline uses weak labels generated by DeepSeek (llm_labeling.py).
Class imbalance is handled via weighted cross-entropy loss.

Track B — Technology Innovation & Ecosystem Tracking
"""

import os
import numpy as np
import pandas as pd
import torch
from torch.utils.data import Dataset, DataLoader
from transformers import (
    DistilBertTokenizerFast,
    DistilBertForSequenceClassification,
    get_linear_schedule_with_warmup,
)
from torch.optim import AdamW
from sklearn.metrics import classification_report, f1_score
from src.utils import LABEL2ID, ID2LABEL

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------

MODEL_NAME = "distilbert-base-uncased"
TRAIN_PATH = "data/splits/train.csv"
VAL_PATH = "data/splits/val.csv"
OUTPUT_DIR = "models/trained_models"

MAX_LEN = 256
BATCH_SIZE = 16
EPOCHS = 4
LEARNING_RATE = 2e-5
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
np.random.seed(RANDOM_SEED)

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {DEVICE}")


# ---------------------------------------------------------------------------
# Dataset
# ---------------------------------------------------------------------------

class RepoDataset(Dataset):
    def __init__(self, df: pd.DataFrame, tokenizer, max_len: int = MAX_LEN):
        self.summaries = df["summary"].tolist()
        self.labels = df["label"].map(LABEL2ID).tolist()
        self.tokenizer = tokenizer
        self.max_len = max_len

    def __len__(self):
        return len(self.summaries)

    def __getitem__(self, idx):
        encoding = self.tokenizer(
            self.summaries[idx],
            max_length=self.max_len,
            padding="max_length",
            truncation=True,
            return_tensors="pt",
        )
        return {
            "input_ids": encoding["input_ids"].squeeze(),
            "attention_mask": encoding["attention_mask"].squeeze(),
            "labels": torch.tensor(self.labels[idx], dtype=torch.long),
        }


# ---------------------------------------------------------------------------
# Class weights (handle imbalance)
# ---------------------------------------------------------------------------

def compute_class_weights(train_df: pd.DataFrame) -> torch.Tensor:
    """Compute inverse-frequency class weights for weighted loss."""
    counts = train_df["label"].map(LABEL2ID).value_counts().sort_index()
    total = counts.sum()
    weights = total / (len(LABEL2ID) * counts)
    weights = weights / weights.sum() * len(LABEL2ID)  # normalize
    print(f"Class weights: { {ID2LABEL[i]: round(w, 3) for i, w in enumerate(weights)} }")
    return torch.tensor(weights.values, dtype=torch.float).to(DEVICE)


# ---------------------------------------------------------------------------
# Training loop
# ---------------------------------------------------------------------------

def train_epoch(model, loader, optimizer, scheduler, class_weights):
    model.train()
    total_loss = 0
    loss_fn = torch.nn.CrossEntropyLoss(weight=class_weights)

    for batch in loader:
        input_ids = batch["input_ids"].to(DEVICE)
        attention_mask = batch["attention_mask"].to(DEVICE)
        labels = batch["labels"].to(DEVICE)

        optimizer.zero_grad()
        outputs = model(input_ids=input_ids, attention_mask=attention_mask)
        loss = loss_fn(outputs.logits, labels)
        loss.backward()

        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
        optimizer.step()
        scheduler.step()

        total_loss += loss.item()

    return total_loss / len(loader)


def evaluate(model, loader):
    model.eval()
    all_preds, all_labels = [], []

    with torch.no_grad():
        for batch in loader:
            input_ids = batch["input_ids"].to(DEVICE)
            attention_mask = batch["attention_mask"].to(DEVICE)
            labels = batch["labels"].to(DEVICE)

            outputs = model(input_ids=input_ids, attention_mask=attention_mask)
            preds = torch.argmax(outputs.logits, dim=1)

            all_preds.extend(preds.cpu().numpy())
            all_labels.extend(labels.cpu().numpy())

    f1 = f1_score(all_labels, all_preds, average="macro")
    report = classification_report(
        all_labels, all_preds,
        target_names=list(ID2LABEL.values()),
        zero_division=0,
    )
    return f1, report, all_preds, all_labels


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def run(
    train_path: str = TRAIN_PATH,
    val_path: str = VAL_PATH,
    output_dir: str = OUTPUT_DIR,
):
    print("=" * 60)
    print("DistilBERT Fine-Tuning — Technology Maturity Classifier")
    print("=" * 60)

    # Load data
    train_df = pd.read_csv(train_path)
    val_df = pd.read_csv(val_path)
    print(f"Train: {len(train_df)} | Val: {len(val_df)}")

    # Tokenizer & model
    tokenizer = DistilBertTokenizerFast.from_pretrained(MODEL_NAME)
    model = DistilBertForSequenceClassification.from_pretrained(
        MODEL_NAME,
        num_labels=len(LABEL2ID),
        id2label=ID2LABEL,
        label2id=LABEL2ID,
    ).to(DEVICE)

    # Datasets & loaders
    train_dataset = RepoDataset(train_df, tokenizer)
    val_dataset = RepoDataset(val_df, tokenizer)
    train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True)
    val_loader = DataLoader(val_dataset, batch_size=BATCH_SIZE)

    # Class weights
    class_weights = compute_class_weights(train_df)

    # Optimizer & scheduler
    optimizer = AdamW(model.parameters(), lr=LEARNING_RATE, weight_decay=0.01)
    total_steps = len(train_loader) * EPOCHS
    scheduler = get_linear_schedule_with_warmup(
        optimizer,
        num_warmup_steps=int(0.1 * total_steps),
        num_training_steps=total_steps,
    )

    # Training
    best_f1 = 0
    best_epoch = 0

    for epoch in range(1, EPOCHS + 1):
        print(f"\nEpoch {epoch}/{EPOCHS}")
        train_loss = train_epoch(model, train_loader, optimizer, scheduler, class_weights)
        val_f1, val_report, _, _ = evaluate(model, val_loader)

        print(f"  Train loss : {train_loss:.4f}")
        print(f"  Val F1 (macro): {val_f1:.4f}")
        print(f"\n{val_report}")

        if val_f1 > best_f1:
            best_f1 = val_f1
            best_epoch = epoch
            os.makedirs(output_dir, exist_ok=True)
            model.save_pretrained(output_dir)
            tokenizer.save_pretrained(output_dir)
            print(f"  ✓ Best model saved (epoch {epoch}, F1={val_f1:.4f})")

    print(f"\nTraining complete. Best Val F1: {best_f1:.4f} at epoch {best_epoch}")
    print(f"Model saved to: {output_dir}")

    return model, tokenizer


if __name__ == "__main__":
    run()
